@startuml
'https://plantuml.com/sequence-diagram

autonumber

策略 -> order: buy/sell
order --> order: 获取当前可用余额
order --> order: 可用余额的仓位/n
order --> order: 设置操作过期时间,设置止损，只赢价格,逐仓
order-->oks: request 下单请求
oks<--order: 记录结果
@enduml