#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

: "${MYSQL_CONTAINER:=mysql}"
: "${MYSQL_USER:=root}"
: "${MYSQL_PASSWORD:=example}"
: "${MYSQL_DATABASE:=test}"
: "${POSTGRES_CONTAINER:=postgres}"
: "${POSTGRES_USER:=postgres}"
: "${POSTGRES_DB:=quant_core}"
: "${QUANT_CORE_STRATEGY_EXCHANGE:=binance}"
: "${MIGRATION_WORKDIR:=/tmp/rust_quant_mysql_to_quant_core}"
: "${CANDLE_CONFLICT_MODE:=keep_pg}"

MYSQL_SECURE_DIR="/var/lib/mysql-files"
RUN_ID="rq_legacy_migrate_$(date +%Y%m%d%H%M%S)"
MYSQL_EXPORT_DIR="${MYSQL_SECURE_DIR}/${RUN_ID}"
HOST_EXPORT_DIR="${MIGRATION_WORKDIR}/${RUN_ID}"
POSTGRES_IMPORT_DIR="/tmp/${RUN_ID}"

mysql_exec() {
    podman exec "${MYSQL_CONTAINER}" mysql \
        -u"${MYSQL_USER}" \
        -p"${MYSQL_PASSWORD}" \
        -D "${MYSQL_DATABASE}" \
        --batch \
        --raw \
        "$@"
}

mysql_scalar() {
    mysql_exec --skip-column-names -e "$1" 2>/dev/null | tail -n 1
}

mysql_table_exists() {
    local table="$1"
    local exists
    exists="$(mysql_scalar "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${MYSQL_DATABASE}' AND table_name='${table}';")"
    [[ "${exists}" == "1" ]]
}

psql_exec() {
    podman exec -i "${POSTGRES_CONTAINER}" psql \
        -U "${POSTGRES_USER}" \
        -d "${POSTGRES_DB}" \
        -v ON_ERROR_STOP=1 \
        "$@"
}

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "$1 is required" >&2
        exit 1
    fi
}

quote_pg_ident() {
    local ident="$1"
    printf '"%s"' "${ident//\"/\"\"}"
}

assert_safe_table_name() {
    local table="$1"
    if [[ ! "${table}" =~ ^[a-z0-9_][a-z0-9_-]*$ ]]; then
        echo "Unsafe table name: ${table}" >&2
        exit 2
    fi
}

join_by_comma() {
    local IFS=","
    echo "$*"
}

columns_except_id_assignments() {
    local assignments=()
    for col in "$@"; do
        if [[ "${col}" != "id" ]]; then
            assignments+=("${col} = EXCLUDED.${col}")
        fi
    done
    join_by_comma "${assignments[@]}"
}

columns_except_id_select() {
    local selects=()
    for col in "$@"; do
        if [[ "${col}" != "id" ]]; then
            selects+=("${col}")
        fi
    done
    join_by_comma "${selects[@]}"
}

create_candle_partition() {
    local table="$1"
    assert_safe_table_name "${table}"
    local pg_table
    pg_table="$(quote_pg_ident "${table}")"
    psql_exec <<SQL >/dev/null
CREATE TABLE IF NOT EXISTS ${pg_table} (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts BIGINT NOT NULL,
    o VARCHAR(20) NOT NULL,
    h VARCHAR(20) NOT NULL,
    l VARCHAR(20) NOT NULL,
    c VARCHAR(20) NOT NULL,
    vol VARCHAR(20) NOT NULL,
    vol_ccy VARCHAR(50) NOT NULL,
    confirm VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (ts)
);
CREATE INDEX IF NOT EXISTS "$(echo "idx_${table}_vol_ccy" | tr '-' '_')" ON ${pg_table} (vol_ccy DESC);
SQL
}

export_mysql_table() {
    local table="$1"
    shift
    local columns=("$@")
    assert_safe_table_name "${table}"

    local outfile="${MYSQL_EXPORT_DIR}/${table}.csv"
    local col_sql
    col_sql="$(join_by_comma "${columns[@]}")"

    podman exec "${MYSQL_CONTAINER}" rm -f "${outfile}"
    mysql_exec -e "
        SELECT ${col_sql}
        FROM \`${table}\`
        INTO OUTFILE '${outfile}'
        CHARACTER SET utf8mb4
        FIELDS TERMINATED BY ','
        OPTIONALLY ENCLOSED BY '\"'
        ESCAPED BY '\\\\'
        LINES TERMINATED BY '\n';
    " >/dev/null 2>&1

    mkdir -p "${HOST_EXPORT_DIR}"
    podman cp "${MYSQL_CONTAINER}:${outfile}" "${HOST_EXPORT_DIR}/${table}.csv"
    podman cp "${HOST_EXPORT_DIR}/${table}.csv" \
        "${POSTGRES_CONTAINER}:${POSTGRES_IMPORT_DIR}/${table}.csv"
    podman exec "${POSTGRES_CONTAINER}" chmod 644 "${POSTGRES_IMPORT_DIR}/${table}.csv"
}

copy_table_by_id() {
    local table="$1"
    shift
    local columns=("$@")
    local pg_table
    local col_sql
    local update_sql

    pg_table="$(quote_pg_ident "${table}")"
    col_sql="$(join_by_comma "${columns[@]}")"
    update_sql="$(columns_except_id_assignments "${columns[@]}")"

    export_mysql_table "${table}" "${columns[@]}"

    psql_exec \
        -v table="${table}" \
        -v columns="${col_sql}" \
        -v updates="${update_sql}" <<SQL
CREATE TEMP TABLE import_${table} (LIKE ${pg_table} INCLUDING DEFAULTS);
COPY import_${table} (${col_sql})
FROM '${POSTGRES_IMPORT_DIR}/${table}.csv'
WITH (FORMAT csv, NULL '\\N', QUOTE '"', ESCAPE '\');
INSERT INTO ${pg_table} (${col_sql})
SELECT ${col_sql} FROM import_${table}
ON CONFLICT (id) DO UPDATE SET ${update_sql};
SELECT setval(pg_get_serial_sequence('${table}', 'id'), COALESCE((SELECT MAX(id) FROM ${pg_table}), 1), true)
WHERE pg_get_serial_sequence('${table}', 'id') IS NOT NULL;
SQL
}

copy_candle_table() {
    local table="$1"
    local columns=(ts o h l c vol vol_ccy confirm created_at updated_at)
    local pg_table
    local col_sql
    local update_sql
    local conflict_sql

    create_candle_partition "${table}"
    export_mysql_table "${table}" "${columns[@]}"

    pg_table="$(quote_pg_ident "${table}")"
    col_sql="$(join_by_comma "${columns[@]}")"
    update_sql="$(columns_except_id_assignments "${columns[@]}")"

    case "${CANDLE_CONFLICT_MODE}" in
        keep_pg)
            conflict_sql="ON CONFLICT (ts) DO NOTHING"
            ;;
        replace_mysql)
            conflict_sql="ON CONFLICT (ts) DO UPDATE SET ${update_sql}"
            ;;
        *)
            echo "Unsupported CANDLE_CONFLICT_MODE=${CANDLE_CONFLICT_MODE}; expected keep_pg or replace_mysql" >&2
            exit 2
            ;;
    esac

    psql_exec \
        -v table="${table}" <<SQL
CREATE TEMP TABLE import_candles AS SELECT ${col_sql} FROM ${pg_table} WITH NO DATA;
COPY import_candles (${col_sql})
FROM '${POSTGRES_IMPORT_DIR}/${table}.csv'
WITH (FORMAT csv, NULL '\\N', QUOTE '"', ESCAPE '\');
INSERT INTO ${pg_table} (${col_sql})
SELECT ${col_sql} FROM import_candles
${conflict_sql};
SELECT setval(pg_get_serial_sequence('${table}', 'id'), COALESCE((SELECT MAX(id) FROM ${pg_table}), 1), true)
WHERE pg_get_serial_sequence('${table}', 'id') IS NOT NULL;
SQL
}

sync_strategy_configs_projection() {
    psql_exec -v exchange="${QUANT_CORE_STRATEGY_EXCHANGE}" <<'SQL'
CREATE OR REPLACE FUNCTION pg_temp.try_jsonb(raw_value text)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
BEGIN
    IF raw_value IS NULL OR btrim(raw_value) = '' THEN
        RETURN '{}'::jsonb;
    END IF;
    RETURN raw_value::jsonb;
EXCEPTION WHEN others THEN
    RETURN '{}'::jsonb;
END;
$$;

UPDATE strategy_configs
SET legacy_id = NULL
WHERE legacy_id IS NOT NULL
  AND version NOT LIKE 'legacy-mysql-%';

WITH src AS (
    SELECT
        id AS legacy_id,
        lower(strategy_type) AS strategy_key,
        lower(strategy_type) AS strategy_name,
        ('legacy-mysql-' || id::text)::varchar AS version,
        :'exchange'::varchar AS exchange,
        inst_id AS symbol,
        time AS timeframe,
        is_deleted = 0 AS enabled,
        pg_temp.try_jsonb(value) || jsonb_build_object(
            '_migration',
            jsonb_build_object(
                'source', 'legacy_mysql.strategy_config',
                'legacy_id', id,
                'tags', tags,
                'kline_start_time', kline_start_time,
                'kline_end_time', kline_end_time,
                'final_fund', final_fund
            )
        ) AS config,
        pg_temp.try_jsonb(risk_config) AS risk_config,
        created_at,
        COALESCE(updated_at, created_at) AS updated_at
    FROM strategy_config
)
INSERT INTO strategy_configs (
    legacy_id,
    strategy_key,
    strategy_name,
    version,
    exchange,
    symbol,
    timeframe,
    enabled,
    config,
    risk_config,
    created_at,
    updated_at
)
SELECT
    legacy_id,
    strategy_key,
    strategy_name,
    version,
    exchange,
    symbol,
    timeframe,
    enabled,
    config,
    risk_config,
    created_at,
    updated_at
FROM src
ON CONFLICT (strategy_key, version, exchange, symbol, timeframe)
DO UPDATE SET
    legacy_id = EXCLUDED.legacy_id,
    strategy_name = EXCLUDED.strategy_name,
    enabled = EXCLUDED.enabled,
    config = EXCLUDED.config,
    risk_config = EXCLUDED.risk_config,
    updated_at = EXCLUDED.updated_at;
SQL
}

print_count_check() {
    local table="$1"
    assert_safe_table_name "${table}"
    if ! mysql_table_exists "${table}"; then
        printf "%-36s mysql=%-10s postgres=%s\n" "${table}" "missing" "structure-only"
        return
    fi
    local mysql_count
    local pg_count
    local pg_table
    mysql_count="$(mysql_scalar "SELECT COUNT(*) FROM \`${table}\`;")"
    pg_table="$(quote_pg_ident "${table}")"
    pg_count="$(
        podman exec "${POSTGRES_CONTAINER}" psql \
            -U "${POSTGRES_USER}" \
            -d "${POSTGRES_DB}" \
            -Atc "SELECT COUNT(*) FROM ${pg_table};" 2>/dev/null | tail -n 1
    )"
    printf "%-36s mysql=%-10s postgres=%s\n" "${table}" "${mysql_count}" "${pg_count}"
}

main() {
    require_command podman

    cd "${REPO_ROOT}"

    if command -v pgloader >/dev/null 2>&1; then
        echo "pgloader available: $(command -v pgloader)"
    else
        echo "pgloader not found; using container-local CSV export plus Postgres COPY"
    fi

    echo "Preparing quant_core DDL"
    ./scripts/dev/ddl_smoke.sh >/dev/null

    podman exec "${MYSQL_CONTAINER}" mkdir -p "${MYSQL_EXPORT_DIR}"
    podman exec "${MYSQL_CONTAINER}" chown mysql:mysql "${MYSQL_EXPORT_DIR}" || true
    podman exec "${POSTGRES_CONTAINER}" mkdir -p "${POSTGRES_IMPORT_DIR}"
    podman exec "${POSTGRES_CONTAINER}" chmod 755 "${POSTGRES_IMPORT_DIR}"
    mkdir -p "${HOST_EXPORT_DIR}"
    local candle_table_list="${HOST_EXPORT_DIR}/legacy_candle_tables.txt"
    mysql_exec --skip-column-names -e "
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema='${MYSQL_DATABASE}'
          AND table_name REGEXP '^[a-z0-9]+-usdt-swap_candles_'
        ORDER BY table_name;
    " 2>/dev/null >"${candle_table_list}"

    echo "Migrating fixed legacy tables"
    copy_table_by_id strategy_config \
        id strategy_type inst_id value risk_config tags time created_at updated_at \
        kline_start_time kline_end_time final_fund is_deleted

    echo "Skipping historical backtest/log data; keeping table structure only:"
    for table in back_test_log back_test_detail back_test_analysis filtered_signal_log; do
        printf "  %s\n" "${table}"
    done

    echo "Migrating market auxiliary tables"
    copy_table_by_id funding_rates \
        id inst_id funding_time funding_rate method next_funding_rate next_funding_time \
        min_funding_rate max_funding_rate sett_funding_rate sett_state premium ts \
        realized_rate interest_rate created_at updated_at
    copy_table_by_id tickers_data \
        id inst_type inst_id last last_sz ask_px ask_sz bid_px bid_sz open24h high24h \
        low24h vol_ccy24h vol24h sod_utc0 sod_utc8 ts
    if mysql_table_exists external_market_snapshots; then
        copy_table_by_id external_market_snapshots \
            id source symbol metric_type metric_time funding_rate premium open_interest \
            oracle_price mark_price long_short_ratio raw_payload created_at updated_at
    fi
    if mysql_table_exists tickers_volume; then
        copy_table_by_id tickers_volume id inst_id period ts oi vol
    else
        echo "Skipping tickers_volume data: MySQL table does not exist; Postgres keeps structure only"
    fi

    echo "Migrating legacy candle partitions"
    echo "Candle conflict mode: ${CANDLE_CONFLICT_MODE}"
    while IFS= read -r candle_table <&3; do
        [[ -z "${candle_table}" ]] && continue
        copy_candle_table "${candle_table}"
    done 3<"${candle_table_list}"

    echo "Syncing legacy strategy_config into quant_core.strategy_configs projection"
    sync_strategy_configs_projection

    echo
    echo "Row count check"
    for table in \
        strategy_config funding_rates tickers_data external_market_snapshots tickers_volume
    do
        print_count_check "${table}"
    done

    echo
    echo "Structure-only backtest/runtime/operation log tables (history intentionally not migrated):"
    for table in \
        back_test_log back_test_detail back_test_analysis filtered_signal_log \
        dynamic_config_log strategy_run signal_snapshot_log risk_decision_log order_decision_log \
        strategy_job_signal_log orders order_state_log positions portfolio_snapshot_log
    do
        printf "  %s\n" "${table}"
    done
    while IFS= read -r candle_table <&3; do
        [[ -z "${candle_table}" ]] && continue
        print_count_check "${candle_table}"
    done 3<"${candle_table_list}"

    echo
    echo "CSV workdir: ${HOST_EXPORT_DIR}"
}

main "$@"
